# This file is autogenerated. Please do not edit
import struct

class TcpBaseClient:
    def auto_heading_on(self):
        command_identifier = b'h'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_heading_off(self):
        command_identifier = b'H'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_depth_on(self):
        command_identifier = b'd'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_depth_off(self):
        command_identifier = b'D'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def set_lights(self, brightness_upper, brightness_lower):
        command_identifier = b'l'
        msg = command_identifier
        msg += struct.pack('BB', brightness_upper, brightness_lower)
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def ping(self):
        command_identifier = b'p'
        msg = command_identifier
        try:
            self.send_msg(msg)
            reply = self.receive_msg()
            self.check_reply(reply, b'P')
        except IOError:
            pass

