# This file is autogenerated. Please do not edit
import struct


class TcpCommands:
    def motion_input(self, surge_motion_input, sway_motion_input, heave_motion_input, yaw_motion_input, slow_input, boost_input):
        command_identifier = b'j'
        msg = command_identifier
        msg += struct.pack('ffffff', surge_motion_input, sway_motion_input, heave_motion_input, yaw_motion_input, slow_input, boost_input)
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_heading_on(self):
        command_identifier = b'h'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_heading_off(self):
        command_identifier = b'H'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_depth_on(self):
        command_identifier = b'd'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def auto_depth_off(self):
        command_identifier = b'D'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def set_lights(self, brightness_upper, brightness_lower):
        command_identifier = b'l'
        msg = command_identifier
        msg += struct.pack('BB', brightness_upper, brightness_lower)
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def ping(self):
        command_identifier = b'p'
        msg = command_identifier
        try:
            self.send_msg(msg)
            reply = self.receive_msg()
            self.check_reply(reply, b'P')
        except IOError:
            pass

    def start_recording(self):
        command_identifier = b'r'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

    def stop_recording(self):
        command_identifier = b'R'
        msg = command_identifier
        try:
            self.send_msg(msg)
        except IOError:
            pass

