#!/usr/bin/env python3
import hashlib
import json
import os
from collections import OrderedDict


def md5(fname):
    hash_md5 = hashlib.md5()
    with open(fname, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()


def generate():
    data = json.loads(
        open("ProtocolDefinitions/udp_protocol.json").read(),
        object_pairs_hook=OrderedDict,
    )
    protocol_md5 = md5("ProtocolDefinitions/udp_protocol.json")
    generator_script_md5 = md5("generators/generate_udp_protocol.py")
    data_file = f"""# -*- coding: utf-8 -*-
# This file is autogenerated. Please do not edit
from collections import OrderedDict
_json_hash = "{protocol_md5}"
_generator_hash = "{generator_script_md5}"
protocol_data = {str(data)}

"""
    with open(
        os.path.join("legacyprotocol", "blueye", "legacyprotocol", "udp_protocol_dict.py"),
        "w",
    ) as f:
        f.write(data_file)
