name: Publish Release

on:
  release:
    types: [created]

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.11"
      - name: Build package with poetry
        run: uv build protocol

      - name: Publish to PyPi
        run: uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/blueye_protocol-*
