name: Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          version: "0.12.15"
      - name: Install dependencies
        run: uv sync --locked --all-packages
      - name: Run tests
        run: uv run invoke test
      - name: Run style checker
        run: uv run ruff check
