name: Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
         version: "0.7.11"
      - name: Install dependencies
        run: uv sync --all-packages
      - name: Run tests
        run: uv run invoke test
      - name: Run style checker
        run: uv run ruff check
