name: Update protocol

on: [repository_dispatch]

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.11"
      - name: Install dependencies
        run: uv sync --all-packages
      - name: Update ProtocolDefinitions
        working-directory: ProtocolDefinitions
        run: git fetch && git checkout ${{ github.event.client_payload.sha }}
      - name: Generate UDP protocol
        run: uv run invoke generate-udp
      - name: Generate TCP protocol
        run: uv run invoke generate-tcp
      - name: Generate Protobuf protocol
        run: uv run invoke generate-proto
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "protocol legacyprotocol ProtocolDefinitions"
          message: "Update ProtocolDefinitions"
          default_author: github_actions
